[package]
name = "muldiv"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/rust-muldiv"
license = "LGPL-2.1+"

[dependencies]

[dev-dependencies]
num = { version = "0.1.*" }
rand = { version = "0.3.*" }
