[package]
name = "muldiv"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/rust-muldiv"
documentation = "https://sdroege.github.io/rust/rust-muldiv/"
license = "LGPL-2.1+"
keywords = ["integer", "arithmetic", "numerics"]
description = """
Provides a trait for numeric types to perform combined multiplication and
division with overflow protection
"""

[features]
default = []
x86-64-assembly = []

[dependencies]

[dev-dependencies]
num = { version = "0.1.*" }
rand = { version = "0.3.*" }
